#!/usr/bin/env ruby

require 'twitter_oauth'

client = TwitterOAuth::Client.new(
    :consumer_key => 'INSERT CONSUMER KEY HERE',
    :consumer_secret => 'INSERT CONSUMER SECRET HERE'
)

request_token = client.authentication_request_token(
  :oauth_callback => 'oob'
)

puts request_token.authorize_url

print 'Please visit the URL and enter the code: '
code = gets.strip

access_token = client.authorize(
  request_token.token,
  request_token.secret,
  :oauth_verifier => code
)

puts "Success: #{client.authorized?}"

puts "oauth key: #{access_token.token}"
puts "oauth secret: #{access_token.secret}"