#!/usr/bin/env ruby

beginning = Time.now

require 'twitter'
require 'twitter_oauth'

#init client
client = Twitter::REST::Client.new do |config|
  config.consumer_key        = 'XYZ'
  config.consumer_secret     = 'XYZ'
  config.access_token        = 'XYZ'
  config.access_token_secret = 'XYZ'
end


if(ARGV[0].nil?)
	puts "Enter some Arguments" #No argument
elsif(ARGV[1].nil?)
	client.update(ARGV[0]) #Only tweet
elsif(ARGV[2].nil?)
	client.update_with_media(ARGV[0], File.new(ARGV[1])) #tweet with picture
else
	client.update_with_media(
		ARGV[0], 
		File.new(ARGV[1]), 
		:lat => ARGV[2], 
		:long =>ARGV[3] , 
		:display_coordinates => true
	)

end

puts "\nSuccess!\nTweet sent in #{(Time.now - beginning)*1000} ms\n\n"
